var surah=document.getElementById('surah');
    var pilih = document.getElementById('pilih');
    var kontrol=document.getElementById('kontrol');
    surah.innerHTML=`
    <option>--Pilih surat--</option>      
<option value="001">[1] Al-Fatihah</option>
<option value="002">[2] Al-Baqarah</option>
<option value="003">[3] Ali-Imran</option>
<option value="004">[4] An-Nisaa'</option>
<option value="005">[5] Al-Maa-idah</option>
<option value="006">[6] Al-An'aam</option>
<option value="007">[7] Al-A'raaf</option>
<option value="008">[8] Al-Anfaal</option>
<option value="009">[9] At-Taubah</option>
<option value="010">[10] Yunus</option>
<option value="011">[11] Hud</option>
<option value="012">[12] Yusuf</option>
<option value="013">[13] Ar-Ra'd</option>
<option value="014">[14] Ibrahim</option>
<option value="015">[15] Al-Hijr</option>
<option value="016">[16] An-Nahl</option>
<option value="017">[17] Al-Isra'</option>
<option value="018">[18] Al-Kahfi</option>
<option value="019">[19] Maryam</option>
<option value="020">[20] Thaha</option>
<option value="021">[21] Al-Anbiyaa'</option>
<option value="022">[22] Al-Hajj</option>
<option value="023">[23] Al-Mu'minuun</option>
<option value="024">[24] An-Nuur</option>
<option value="025">[25] Al-Furqaan</option>
<option value="026">[26] Asy-Syu'araa'</option>
<option value="027">[27] An-Naml</option>
<option value="028">[28] Al-Qashash</option>
<option value="029">[29] Al-Ankabut</option>
<option value="030">[30] Ar-Ruum</option>
<option value="031">[31] Luqman</option>
<option value="032">[32] As-Sajadah</option>
<option value="033">[33] Al-Ahzab</option>
<option value="034">[34] Saba'</option>
<option value="035">[35] Faathir</option>
<option value="036">[36] Yaa Siin</option>
<option value="037">[37] Ash-Shaffaat</option>
<option value="038">[38] Shaad</option>
<option value="039">[39] Az-Zumar</option>
<option value="040">[40] Al-Mu'min</option>
<option value="041">[41] Fush Shilat</option>
<option value="042">[42] Asy-Syuura</option>
<option value="043">[43] Az-Zukhruf</option>
<option value="044">[44] Ad-Dukhaan</option>
<option value="045">[45] Al-Jaatsiyah</option>
<option value="046">[46] Al-Ahqaaf</option>
<option value="047">[47] Muhammad</option>
<option value="048">[48] Al-Fath</option>
<option value="049">[49] Al-Hujurat</option>
<option value="050">[50] Qaaf</option>
<option value="051">[51] Adz-Dzaariyaat</option>
<option value="052">[52] Ath-Thuur</option>
<option value="053">[53] An-Najm</option>
<option value="054">[54] Al-Qamar</option>
<option value="055">[55] Ar-Rahmaan</option>
<option value="056">[56] Al-Waaqiah</option>
<option value="057">[57] Al-Hadiid</option>
<option value="058">[58] Al-Mujaadilah</option>
<option value="059">[59] Al-Hasyr</option>
<option value="060">[60] Al-Mumtahanah</option>
<option value="061">[61] Ash-Shaff</option>
<option value="062">[62] Al-Jumu'ah</option>
<option value="063">[63] Al-Munaafiquun</option>
<option value="064">[64] At-Taghaabun</option>
<option value="065">[65] Ath-Thalaaq</option>
<option value="066">[66] At-Tahrim</option>
<option value="067">[67] Al-Mulk</option>
<option value="068">[68] Al-Qalam</option>
<option value="069">[69] Al-Haaqqah</option>
<option value="070">[70] Al-Ma'aarij</option>
<option value="071">[71] Nuh</option>
<option value="072">[72] Al-Jin</option>
<option value="073">[73] Al-Muzzammil</option>
<option value="074">[74] Al-Muddatstsir</option>
<option value="075">[75] Al-Qiyaamah</option>
<option value="076">[76] Al-Insaan</option>
<option value="077">[77] Al-Mursalaat</option>
<option value="078">[78] An-Naba'</option>
<option value="079">[79] An-Naazi'aat</option>
<option value="080">[80] 'Abasa</option>
<option value="081">[81] At-Takwir</option>
<option value="082">[82] Al-Infithar</option>
<option value="083">[83] Al-Muthaffifiin</option>
<option value="084">[84] Al-Insyiqaaq</option>
<option value="085">[85] Al-Buruuj</option>
<option value="086">[86] Ath-Thaariq</option>
<option value="087">[87] Al-A'laa</option>
<option value="088">[88] Al-Ghaasyiyah</option>
<option value="089">[89] Al-Fajr</option>
<option value="090">[90] Al-Balad</option>
<option value="091">[91] Asy-Syams</option>
<option value="092">[92] Al-Lail</option>
<option value="093">[93] Ad-Dhuhaa</option>
<option value="094">[94] Alam-Nasyrah</option>
<option value="095">[95] At-Tiin</option>
<option value="096">[96] Al-'Alaq</option>
<option value="097">[97] Al-Qadar</option>
<option value="098">[98] Al-Bayyinah</option>
<option value="099">[99] Al-Zalzalah</option>
<option value="100">[100] Al-'Aadiyaat</option>
<option value="101">[101] Al-Qaari'ah</option>
<option value="102">[102] At-Takaatsur</option>
<option value="103">[103] Al-'Ashr</option>
<option value="104">[104] Al-Humazah</option>
<option value="105">[105] Al-Fiil</option>
<option value="106">[106] Al-Quraisy</option>
<option value="107">[107] Al-Maa'un</option>
<option value="108">[108] Al-Kautsar</option>
<option value="109">[109] Al-Kaafiruun</option>
<option value="110">[110] An-Nashr</option>
<option value="111">[111] Al-Lahab</option>
<option value="112">[112] Al-Ikhlash</option>
<option value="113">[113] Al-Falaq</option>
<option value="114">[114] An-Naas</option>
    `;
    pilih.addEventListener('click', function(){
      if(surah.value=='--Pilih surat--'){
        kontrol.innerHTML='<div class="notes2"><b>Catatan:</b><br><i>Maaf, silahkan pilih surat dulu!</i></div>';
      }else{
      kontrol.innerHTML='<b>Pemutar</b><br><audio src="https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/'+ surah.value +'.mp3" controls autoplay></audio><br><div class="notes"><b>Catatan:</b><ul><i><li>Kecepatan respon putar tergantung kualitas jaringan.</li><li>Untuk unduh file mp3 klik/ sentuh titik tiga pada kontrol pemutar.</li><li>Sumber file mp3: download.quranicaudio.com</li></i></ul></div>';
      }
    });